#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# 以下两行会直接打印到生成文件里

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

# sub 是 Perl 的函数/子程序定义关键字，entry 是函数名
sub entry {
    # my 表示声明一个局部变量，Perl 的普通标量变量以 $ 开头
    # shift 是 Perl 的一个操作，用来从参数列表中取出第一个参数
    my $prefix = "sys_";
    my $name = shift;

    # sbrk 特殊是因为这个版本的 xv6 在用户态（ulib.c）里自己也定义了一个叫 sbrk 的函数
    # 如果生成的汇编桩也叫 sbrk，链接时就会出现两个同名全局符号
    if ($name eq "sbrk") {
        print ".global $prefix$name\n";
        print "$prefix$name:\n";
    } else {
        print ".global $name\n";
        print "$name:\n";
    }

    # 将系统调用号放入 a7 寄存器，a7 是 RISC-V 的约定寄存器，用于存放系统调用号
    # SYS_${name} 是在 kernel/syscall.h 里定义的系统调用号宏，li 是 RISC-V 汇编指令
    # 表示立即数加载到寄存器，ecall：环境调用指令，触发系统调用，ret：返回指令
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
entry("sync");
